# Generated by Django 4.1 on 2024-10-16 16:47

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, upload_to=cinema.models.image_path),
        ),
    ]
